version: "3.9"

services:
    # Laravel App Service
    laravelapp:
        container_name: laravelapp
        image: elloston/laravelapp:1.0.0
        build:
            context: . # Build context is the current directory
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db # Depend on the db service

    # PostgreSQL Database Service
    db:
        container_name: db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data # Mount volume for persistent data

volumes:
    pgdata: {} # Define a volume for PostgreSQL data
